Upgrade to Vert.x 3.6.3 and utilize non-threaded worker verticles
glencoesoftware/omero-ms-backbone pull request #2
Opened 2019-04-02 09:06 UTC by chris-allan

As of Vert.x 3.6.0 threaded worker verticles are deprecated (eclipse-vertx/vert.x#2702). They will be removed in Vert.x 4.0.0. We previously used the threaded style because it allowed us to simply instantiate the verticle ourselves, provide constructor arguments during instantiation, and resulted in a single instance. As a consequence dependency injection and verticle factories were not something that we needed to be concerned about.

This PR switches to a worker verticle style that is multi-instance and provides a Spring based dependency injection aware verticle factory. The default worker pool size is now `core count * 2` and can be configured using the `omero.ms.backbone.worker_pool_size` OMERO server configuration property. Because of the OMERO server's dependency on Spring 3 the use of Java 8+ lambda expressions are not permitted in the directly accessible verticle code.

2019-04-02 15:38 UTC, kkoz commented on src/dist/hazelcast.xml.example
> +            <aws enabled="false">
Might want to remove aws tag

2019-04-02 17:02 UTC, kkoz requested changes

2019-04-02 17:02 UTC, kkoz commented on src/dist/hazelcast.xml.example
> +            <aws enabled="false">
Might want to remove aws tag

2019-04-02 17:54 UTC, chris-allan commented on src/dist/hazelcast.xml.example
> +            <aws enabled="false">
It's the default configuration copied verbatim from the Hazelcast JARs.

2019-04-03 13:45 UTC, kkoz approved these changes

2019-04-03 13:45 UTC, merged